all:
  children:
    eos:
      hosts:
        R1: { ansible_host: 192.0.2.11 }
        R2: { ansible_host: 192.0.2.12 }
        R3: { ansible_host: 192.0.2.13 }
      vars:
        ansible_connection: network_cli
        ansible_network_os: arista.eos.eos
        ansible_become: yes
        ansible_become_method: enable
