name: Net Deploy

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dryrun:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible & collections (idempotent)
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip
          ansible-galaxy collection install arista.eos ansible.netcommon

      - name: Write vault password
        env: { VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }} }
        run: echo "$VAULT_PASS" > .vault_pass.txt

      - name: Inventory graph
        run: ansible-inventory --graph

      - name: Dry-run with diff
        env: { ANSIBLE_VAULT_PASSWORD_FILE: ./.vault_pass.txt }
        run: ansible-playbook playbooks/10_l3_bgp.yml --check --diff

  deploy:
    needs: dryrun
    if: github.event_name != 'pull_request'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible & collections (idempotent)
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip
          ansible-galaxy collection install arista.eos ansible.netcommon

      - name: Write vault password
        env: { VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }} }
        run: echo "$VAULT_PASS" > .vault_pass.txt

      - name: Deploy
        env: { ANSIBLE_VAULT_PASSWORD_FILE: ./.vault_pass.txt }
        run: ansible-playbook playbooks/10_l3_bgp.yml -vv
